[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify-functions"

[dev]
  command = "npm run dev" 
  targetPort = 5174       
  port = 8888             



[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/upload"
  to = "https://events-sihs.onrender.com/upload/:splat"
  status = 200
  